import { ErrorNote, Loading } from "@/components/AppShell";
import { Button } from "@/components/ui/button";
import { Dialog, DialogBody, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";
import { t, type MessageKey } from "@/i18n/messages";
import { afterPublish, changeSummary, liveGrants } from "@/lib/syllabusPublishState";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Info } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import type { Tree } from "./SyllabusDetail";
import { fieldLabel, problemText, toastError, useSyllabusRefresh } from "./shared";

const toggle = <T,>(list: T[], v: T) => (list.includes(v) ? list.filter((x) => x !== v) : [...list, v]);

/**
 * First publish: what students will see, which groups get it, and that editing stays open.
 * Sending changes: what changed in plain words, and whether students already learning get the update.
 * Version labels are generated by the server.
 */
export function PublishDialog({ tree, open, onOpenChange }: { tree: Tree; open: boolean; onOpenChange: (v: boolean) => void }) {
  const syllabusId = tree.syllabus.id;
  const firstPublish = !tree.syllabus.currentVersionId;
  const refresh = useSyllabusRefresh(syllabusId);
  const utils = trpc.useUtils();
  const preview = trpc.teacher.syllabus.publishPreview.useQuery({ id: syllabusId }, { enabled: open, refetchOnWindowFocus: false });
  const grants = trpc.teacher.syllabus.grants.useQuery({ id: syllabusId }, { enabled: open });
  const groups = trpc.teacher.groups.list.useQuery(undefined, { enabled: open && firstPublish });
  const versions = trpc.teacher.syllabus.versions.useQuery({ id: syllabusId }, { enabled: open && !firstPublish });
  const [groupIds, setGroupIds] = useState<string[]>([]);
  const [moveEnrolled, setMoveEnrolled] = useState(true);
  const [note, setNote] = useState("");
  const [problems, setProblems] = useState<{ code: string; title?: string }[] | null>(null);
  const [busy, setBusy] = useState(false);

  const publish = trpc.teacher.syllabus.publish.useMutation();
  const grant = trpc.teacher.syllabus.grant.useMutation();
  const move = trpc.teacher.syllabus.moveStudents.useMutation();
  const markReady = trpc.teacher.syllabus.markAllReady.useMutation({
    onSuccess: () => {
      toast.success(t("pub.markedReady"));
      setProblems(null);
      refresh();
      void preview.refetch();
    },
    onError: toastError,
  });

  const live = liveGrants(grants.data) ?? [];
  const grantedGroupIds = live.flatMap((g) => (g.groupId ? [g.groupId] : []));
  const enrolled = (versions.data ?? []).reduce((n, v) => n + v.enrolledCount, 0);

  const close = () => {
    onOpenChange(false);
    setProblems(null);
    setGroupIds([]);
    setMoveEnrolled(true);
    setNote("");
  };

  const run = async () => {
    setBusy(true);
    try {
      const r = await publish.mutateAsync({ id: syllabusId, changeNote: note.trim() || undefined });
      if (!r.published) {
        setProblems(r.problems);
        return;
      }
      const plan = afterPublish({ firstPublish, selectedGroupIds: groupIds, grantedGroupIds, moveEnrolled, enrolled });
      if (plan.grant) await grant.mutateAsync({ id: syllabusId, groupIds: plan.grantGroupIds, studentIds: plan.grantStudentIds });
      if (plan.moveAll) await move.mutateAsync({ id: syllabusId, versionId: r.versionId, all: true });
      toast.success(firstPublish ? (plan.grant ? t("pub.doneFirstGroups") : t("pub.doneFirst")) : t("pub.doneSend"));
      refresh();
      void utils.teacher.syllabus.versions.invalidate({ id: syllabusId });
      void utils.teacher.syllabus.grants.invalidate({ id: syllabusId });
      void utils.teacher.syllabus.list.invalidate();
      close();
    } catch (e) {
      toastError(e);
    } finally {
      setBusy(false);
    }
  };

  const p = preview.data;
  const d = p?.diff;
  const shownProblems = problems ?? p?.problems ?? [];
  const notReady = p ? p.notReady.modules + p.notReady.lessons : 0;
  const emptyModules = p ? Math.max(0, p.excluded.modules - p.notReady.modules) : 0;
  const summary = d ? changeSummary(d).map((s) => t(`pub.sum.${s.key}` as MessageKey, s.count === undefined ? undefined : { count: s.count })) : [];

  return (
    <Dialog open={open} onOpenChange={(v) => (v ? onOpenChange(true) : close())}>
      <DialogContent className="max-w-lg">
        <DialogHeader><DialogTitle>{firstPublish ? t("pub.firstTitle") : t("pub.sendTitle")}</DialogTitle></DialogHeader>
        <DialogBody>
          {preview.isLoading ? (
            <Loading />
          ) : preview.error ? (
            <ErrorNote error={preview.error} />
          ) : p && d ? (
            <div className="grid gap-4 text-sm">
              {!p.studentsEnabled && (
                <p role="alert" className="flex items-start gap-2 rounded-xl border border-warning/40 bg-warning-surface p-3 text-warning">
                  <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" aria-hidden />
                  {t("pub.flagOff")}
                </p>
              )}
              {shownProblems.length > 0 && (
                <div role="alert" className="rounded-xl border border-destructive/40 bg-danger-surface p-3 text-destructive">
                  <p className="mb-1 font-medium">{t("syllabus.publish.problems")}</p>
                  <ul className="list-disc space-y-0.5 pl-5">{shownProblems.map((pr, i) => <li key={i}>{problemText(pr)}</li>)}</ul>
                </div>
              )}
              <div className="grid gap-2">
                {firstPublish ? (
                  <p className="text-base font-medium">{t("pub.counts", { modules: p.included.modules, lessons: p.included.lessons })}</p>
                ) : (
                  <p className="text-base font-medium">{summary.length ? t("pub.changed", { what: summary.join(", ") }) : t("pub.noChanges")}</p>
                )}
                {notReady > 0 && (
                  <div className="flex flex-wrap items-center gap-2 rounded-lg border border-warning/40 bg-warning-surface px-3 py-2 text-warning">
                    <span className="min-w-0 flex-1">
                      {t("pub.notReady", {
                        what: [
                          p.notReady.modules ? t("syllabus.count.modules", { count: p.notReady.modules }) : "",
                          p.notReady.lessons ? t("syllabus.count.lessons", { count: p.notReady.lessons }) : "",
                        ].filter(Boolean).join(", "),
                      })}
                    </span>
                    <Button size="sm" variant="outline" disabled={markReady.isPending} onClick={() => markReady.mutate({ id: syllabusId })}>
                      {t("pub.markAllReady")}
                    </Button>
                  </div>
                )}
                {emptyModules > 0 && <p className="text-foreground-secondary">{t("pub.emptyModules", { count: emptyModules })}</p>}
              </div>
              {firstPublish && (
                <fieldset className="grid gap-2">
                  <legend className="mb-1 font-medium">{t("pub.groupsTitle")}</legend>
                  <div className="max-h-44 space-y-1 overflow-y-auto rounded-lg border p-2">
                    {(groups.data ?? []).map((g) => {
                      const already = grantedGroupIds.includes(g.id);
                      return (
                        <label key={g.id} className="flex items-center gap-2">
                          <input type="checkbox" className="accent-link" disabled={already} checked={already || groupIds.includes(g.id)} onChange={() => setGroupIds(toggle(groupIds, g.id))} />
                          <span className="min-w-0 break-words">{g.name}</span>
                          {already && <span className="text-xs text-muted-foreground">({t("pub.alreadyOpen")})</span>}
                        </label>
                      );
                    })}
                    {groups.isLoading && <Loading />}
                    {!groups.isLoading && !groups.data?.length && <div className="text-xs text-muted-foreground">{t("modules.noGroups")}</div>}
                  </div>
                  <p className="flex items-start gap-1.5 text-xs text-muted-foreground">
                    <Info className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
                    <span>{t("pub.groupsHelp")}</span>
                  </p>
                </fieldset>
              )}
              {!firstPublish && enrolled > 0 && (
                <label className="flex items-start gap-2">
                  <input type="checkbox" className="mt-0.5 accent-link" checked={moveEnrolled} onChange={(e) => setMoveEnrolled(e.target.checked)} />
                  <span>
                    {t("pub.moveEnrolled")}
                    <span className="mt-0.5 block text-xs text-muted-foreground">
                      {moveEnrolled ? t("pub.moveEnrolledHelp", { count: enrolled }) : t("pub.keepEnrolled")}
                    </span>
                  </span>
                </label>
              )}
              <details>
                <summary className="cursor-pointer text-xs text-foreground-secondary">{t("pub.noteToggle")}</summary>
                <label className="mt-2 block">
                  <span className={`sr-only ${fieldLabel}`}>{t("pub.noteToggle")}</span>
                  <Textarea rows={3} maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} placeholder={t("pub.notePlaceholder")} />
                </label>
              </details>
              {firstPublish && <p className="text-muted-foreground">{t("pub.editLater")}</p>}
            </div>
          ) : null}
        </DialogBody>
        <DialogFooter>
          <Button variant="outline" onClick={close}>{t("common.cancel")}</Button>
          <Button disabled={!p || shownProblems.length > 0 || busy || markReady.isPending} onClick={() => void run()}>
            {busy ? t("syllabus.publish.publishing") : firstPublish ? t("syllabus.publish.confirm") : t("syllabus.action.sendChanges")}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
