import { TRPCError } from "@trpc/server";

export type AppErrorCode =
  | "NOT_FOUND"
  | "FORBIDDEN"
  | "INVITE_NOT_FOUND"
  | "INVITE_CODE_INACTIVE"
  | "INVITE_CODE_EXPIRED"
  | "GROUP_NOT_ACCEPTING"
  | "STUDENT_NOT_FOUND"
  | "ALREADY_MEMBER"
  | "EMAIL_INVITE_NOT_FOUND"
  | "EMAIL_INVITE_EXPIRED"
  | "EMAIL_INVITE_MISMATCH"
  | "NO_QUESTIONS"
  | "INVALID_QUESTION"
  | "NOT_DRAFT"
  | "NOT_PUBLISHED"
  | "NO_ACCESS"
  | "NOT_STARTED"
  | "CLOSED"
  | "NO_ATTEMPTS_LEFT"
  | "ATTEMPT_CLOSED"
  | "UNKNOWN_QUESTION"
  | "NOT_REVIEWABLE"
  | "POINTS_OUT_OF_RANGE"
  | "RATE_LIMITED"
  | "DATABASE_UNAVAILABLE"
  | "AI_UNAVAILABLE"
  | "AI_INVALID_OUTPUT"
  | "AI_USAGE_LIMIT_REACHED"
  | "AI_REVIEW_IN_PROGRESS"
  | "AI_REVIEW_DAILY_LIMIT"
  | "AI_ANSWER_KEY_FAILED"
  | "DEMO_DISABLED"
  | "CANNOT_JOIN_OWN_GROUP"
  | "NO_WORKSPACE"
  | "WORKSPACE_LIMIT"
  | "WORKSPACE_NOT_ALLOWED"
  | "CONTEXT_UNAVAILABLE"
  | "PARTNER_EXISTS"
  | "ACCOUNT_SUSPENDED"
  | "CANNOT_TARGET_SELF"
  | "TARGET_IS_SUPER_ADMIN"
  | "ALREADY_SUSPENDED"
  | "NOT_SUSPENDED"
  | "ROLE_NOT_GRANTABLE"
  | "ALREADY_HAS_ROLE"
  | "LAST_SUPER_ADMIN"
  | "INVALID_TRANSITION"
  | "AUDIT_UNSAFE_METADATA"
  | "FILE_NOT_FOUND"
  | "FILE_TOO_LARGE"
  | "FILE_TYPE_NOT_ALLOWED"
  | "TASK_NO_ACCESS"
  | "TASK_GROUPS_REQUIRED"
  | "INVALID_CREDENTIALS"
  | "GOOGLE_ACCOUNT_NO_PASSWORD"
  | "REGISTRATION_UNAVAILABLE"
  | "INVALID_CURRENT_PASSWORD"
  | "REAUTH_REQUIRED"
  | "PASSWORD_EMAIL_IN_USE"
  | "PASSWORD_NO_EMAIL"
  | "INVITE_LINK_NOT_FOUND"
  | "INVITE_LINK_USED"
  | "INVITE_LINK_EXPIRED"
  | "INVITE_LINK_REVOKED"
  | "INVITE_LINK_BATCH_TOO_LARGE"
  | "SUBMISSION_EMPTY"
  | "SUBMISSION_ALREADY_GRADED"
  | "SYLLABUS_NOT_AVAILABLE"
  | "SYLLABUS_DB_NOT_READY"
  | "SYLLABUS_EMPTY"
  | "SYLLABUS_ASSESSMENT_NOT_PUBLISHED"
  | "SYLLABUS_INVALID_CONTENT"
  | "SYLLABUS_STALE_REVISION"
  | "SYLLABUS_ARCHIVED"
  | "SYLLABUS_NO_ACCESS"
  | "SYLLABUS_LOCKED"
  | "SYLLABUS_NOT_PUBLISHED"
  | "SYLLABUS_INVALID_TARGET"
  | "SYLLABUS_PRACTICE_TASK_IN_USE"
  | "SYLLABUS_PROGRESS_HIDDEN"
  | "SYLLABUS_RETRY_COOLDOWN";

export class AppError extends Error {
  constructor(public readonly code: AppErrorCode) {
    super(code);
  }
}

const HTTP: Partial<Record<AppErrorCode, TRPCError["code"]>> = {
  NOT_FOUND: "NOT_FOUND",
  INVITE_NOT_FOUND: "NOT_FOUND",
  INVITE_CODE_INACTIVE: "PRECONDITION_FAILED",
  INVITE_CODE_EXPIRED: "PRECONDITION_FAILED",
  GROUP_NOT_ACCEPTING: "FORBIDDEN",
  STUDENT_NOT_FOUND: "NOT_FOUND",
  EMAIL_INVITE_NOT_FOUND: "NOT_FOUND",
  EMAIL_INVITE_EXPIRED: "PRECONDITION_FAILED",
  EMAIL_INVITE_MISMATCH: "FORBIDDEN",
  UNKNOWN_QUESTION: "NOT_FOUND",
  FORBIDDEN: "FORBIDDEN",
  NO_ACCESS: "FORBIDDEN",
  NOT_STARTED: "PRECONDITION_FAILED",
  CLOSED: "PRECONDITION_FAILED",
  NOT_PUBLISHED: "PRECONDITION_FAILED",
  NO_ATTEMPTS_LEFT: "PRECONDITION_FAILED",
  ATTEMPT_CLOSED: "PRECONDITION_FAILED",
  NOT_DRAFT: "PRECONDITION_FAILED",
  ALREADY_MEMBER: "CONFLICT",
  RATE_LIMITED: "TOO_MANY_REQUESTS",
  DATABASE_UNAVAILABLE: "INTERNAL_SERVER_ERROR",
  AI_UNAVAILABLE: "PRECONDITION_FAILED",
  AI_INVALID_OUTPUT: "INTERNAL_SERVER_ERROR",
  AI_USAGE_LIMIT_REACHED: "TOO_MANY_REQUESTS",
  AI_REVIEW_IN_PROGRESS: "CONFLICT",
  AI_REVIEW_DAILY_LIMIT: "TOO_MANY_REQUESTS",
  AI_ANSWER_KEY_FAILED: "INTERNAL_SERVER_ERROR",
  DEMO_DISABLED: "FORBIDDEN",
  CANNOT_JOIN_OWN_GROUP: "CONFLICT",
  NO_WORKSPACE: "FORBIDDEN",
  WORKSPACE_LIMIT: "CONFLICT",
  WORKSPACE_NOT_ALLOWED: "FORBIDDEN",
  CONTEXT_UNAVAILABLE: "FORBIDDEN",
  PARTNER_EXISTS: "CONFLICT",
  ACCOUNT_SUSPENDED: "FORBIDDEN",
  CANNOT_TARGET_SELF: "FORBIDDEN",
  TARGET_IS_SUPER_ADMIN: "FORBIDDEN",
  ALREADY_SUSPENDED: "CONFLICT",
  NOT_SUSPENDED: "CONFLICT",
  ROLE_NOT_GRANTABLE: "FORBIDDEN",
  ALREADY_HAS_ROLE: "CONFLICT",
  LAST_SUPER_ADMIN: "CONFLICT",
  INVALID_TRANSITION: "PRECONDITION_FAILED",
  AUDIT_UNSAFE_METADATA: "INTERNAL_SERVER_ERROR",
  FILE_NOT_FOUND: "NOT_FOUND",
  FILE_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  FILE_TYPE_NOT_ALLOWED: "BAD_REQUEST",
  TASK_NO_ACCESS: "FORBIDDEN",
  TASK_GROUPS_REQUIRED: "BAD_REQUEST",
  // Not UNAUTHORIZED: the client treats that as "session expired" and redirects to sign-in.
  INVALID_CREDENTIALS: "BAD_REQUEST",
  GOOGLE_ACCOUNT_NO_PASSWORD: "BAD_REQUEST",
  REGISTRATION_UNAVAILABLE: "CONFLICT",
  INVALID_CURRENT_PASSWORD: "BAD_REQUEST",
  REAUTH_REQUIRED: "FORBIDDEN",
  PASSWORD_EMAIL_IN_USE: "CONFLICT",
  PASSWORD_NO_EMAIL: "BAD_REQUEST",
  INVITE_LINK_NOT_FOUND: "NOT_FOUND",
  INVITE_LINK_USED: "CONFLICT",
  INVITE_LINK_EXPIRED: "PRECONDITION_FAILED",
  INVITE_LINK_REVOKED: "PRECONDITION_FAILED",
  INVITE_LINK_BATCH_TOO_LARGE: "BAD_REQUEST",
  SUBMISSION_EMPTY: "BAD_REQUEST",
  SUBMISSION_ALREADY_GRADED: "CONFLICT",
  SYLLABUS_NOT_AVAILABLE: "FORBIDDEN",
  SYLLABUS_DB_NOT_READY: "PRECONDITION_FAILED",
  SYLLABUS_EMPTY: "PRECONDITION_FAILED",
  SYLLABUS_ASSESSMENT_NOT_PUBLISHED: "PRECONDITION_FAILED",
  SYLLABUS_INVALID_CONTENT: "BAD_REQUEST",
  SYLLABUS_STALE_REVISION: "CONFLICT",
  SYLLABUS_ARCHIVED: "PRECONDITION_FAILED",
  SYLLABUS_NO_ACCESS: "FORBIDDEN",
  SYLLABUS_LOCKED: "FORBIDDEN",
  SYLLABUS_NOT_PUBLISHED: "PRECONDITION_FAILED",
  SYLLABUS_INVALID_TARGET: "BAD_REQUEST",
  SYLLABUS_PRACTICE_TASK_IN_USE: "CONFLICT",
  SYLLABUS_PROGRESS_HIDDEN: "FORBIDDEN",
  SYLLABUS_RETRY_COOLDOWN: "PRECONDITION_FAILED",
};

/** Where an unexpected error happened, for the server log only (never sent to the client). */
export interface ErrorContext {
  path?: string;
  type?: string;
  userId?: number | null;
  workspaceId?: string | null;
}

/** Driver details worth logging (MySQL errno / code / sqlMessage), found anywhere in the cause chain. */
export function errorDetails(error: unknown) {
  let e = error as { errno?: unknown; code?: unknown; sqlMessage?: unknown; cause?: unknown } | undefined;
  for (let i = 0; e && i < 5; i++) {
    if (typeof e.errno === "number" || typeof e.sqlMessage === "string") {
      return { errno: e.errno, code: e.code, sqlMessage: typeof e.sqlMessage === "string" ? e.sqlMessage.slice(0, 300) : undefined };
    }
    e = e.cause as typeof e;
  }
  return {};
}

/** Convert domain errors into tRPC errors; the message stays a stable machine code. */
export function toTrpcError(error: unknown, context: ErrorContext = {}): TRPCError {
  if (error instanceof TRPCError) return error;
  const code = error instanceof AppError ? error.code : error instanceof Error ? error.message : "UNKNOWN";
  const mapped = HTTP[code as AppErrorCode];
  if (mapped) return new TRPCError({ code: mapped, message: code });
  if (error instanceof AppError) return new TRPCError({ code: "BAD_REQUEST", message: code });
  console.error("[Resulio] Unexpected error", { ...context, ...errorDetails(error) }, error);
  return new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "INTERNAL_ERROR" });
}
